In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
a_np = np.array(a)

In [3]:
print(a)
print(a_np)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
a_np.shape

(5,)

In [5]:
b = np.array([[1, 0, 1],
              [0, 1, 0],
              [2, 1, 3]])

In [6]:
print(b.shape)

(3, 3)


In [7]:
print(b)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [8]:
# Transpuesta
print(b.T)

[[1 0 2]
 [0 1 1]
 [1 0 3]]


In [9]:
# Producto punto
np.dot(b, b.T)

array([[ 2,  0,  5],
       [ 0,  1,  1],
       [ 5,  1, 14]])